
                                                <select name="city" class="form-control">
                                                    <option selected disabled>-- Birini seçin --</option>
                                                    <option value="Bakı" @if($user->city == "Bakı") selected @endif>Bakı</option>
                                                    <option value="Ağcabədi" @if($user->city == "Ağcabədi") selected @endif>Ağcabədi</option>
                                                    <option value="Ağdam" @if($user->city == "Ağdam") selected @endif>Ağdam</option>
                                                    <option value="Ağdaş" @if($user->city == "Ağdaş") selected @endif>Ağdaş</option>
                                                    <option value="Ağdərə" @if($user->city == "Ağdərə") selected @endif>Ağdərə</option>
                                                    <option value="Ağstafa" @if($user->city == "Ağstafa") selected @endif>Ağstafa</option>
                                                    <option value="Ağsu" @if($user->city == "Ağsu") selected @endif>Ağsu</option>
                                                    <option value="Astara" @if($user->city == "Astara") selected @endif>Astara</option>
                                                    <option value="Babək" @if($user->city == "Babək") selected @endif>Babək</option>
                                                    <option value="Balakən" @if($user->city == "Balakən") selected @endif>Balakən</option>
                                                    <option value="Beyləqan" @if($user->city == "Beyləqan") selected @endif>Beyləqan</option>
                                                    <option value="Bərdə" @if($user->city == "Bərdə") selected @endif>Bərdə</option>
                                                    <option value="Biləsuvar" @if($user->city == "Biləsuvar") selected @endif>Biləsuvar</option>
                                                    <option value="Cəbrayıl" @if($user->city == "Cəbrayıl") selected @endif>Cəbrayıl</option>
                                                    <option value="Cəlilabad" @if($user->city == "Cəlilabad") selected @endif>Cəlilabad</option>
                                                    <option value="Culfa" @if($user->city == "Culfa") selected @endif>Culfa</option>
                                                    <option value="Daşkəsən" @if($user->city == "Daşkəsən") selected @endif>Daşkəsən</option>
                                                    <option value="Füzuli" @if($user->city == "Füzuli") selected @endif>Füzuli</option>
                                                    <option value="Gədəbəy" @if($user->city == "Gədəbəy") selected @endif>Gədəbəy</option>
                                                    <option value="Gəncə" @if($user->city == "Gəncə") selected @endif>Gəncə</option>
                                                    <option value="Goranboy" @if($user->city == "Goranboy") selected @endif>Goranboy</option>
                                                    <option value="Göyçay" @if($user->city == "Göyçay") selected @endif>Göyçay</option>
                                                    <option value="Göygöl" @if($user->city == "Göygöl") selected @endif>Göygöl</option>
                                                    <option value="Göytəpə" @if($user->city == "Göytəpə") selected @endif>Göytəpə</option>
                                                    <option value="Hacıqabul" @if($user->city == "Hacıqabul") selected @endif>Hacıqabul</option>
                                                    <option value="Horadiz" @if($user->city == "Horadiz") selected @endif>Horadiz</option>
                                                    <option value="Xaçmaz" @if($user->city == "Xaçmaz") selected @endif>Xaçmaz</option>
                                                    <option value="Xankəndi" @if($user->city == "Xankəndi") selected @endif>Xankəndi</option>
                                                    <option value="Xocalı" @if($user->city == "Xocalı") selected @endif>Xocalı</option>
                                                    <option value="Xocavənd" @if($user->city == "Xocavənd") selected @endif>Xocavənd</option>
                                                    <option value="Xızı" @if($user->city == "Xızı") selected @endif>Xızı</option>
                                                    <option value="Xudat" @if($user->city == "Xudat") selected @endif>Xudat</option>
                                                    <option value="İmişli" @if($user->city == "İmişli") selected @endif>İmişli</option>
                                                    <option value="İsmayıllı" @if($user->city == "İsmayıllı") selected @endif>İsmayıllı</option>
                                                    <option value="Kəlbəcər" @if($user->city == "Kəlbəcər") selected @endif>Kəlbəcər</option>
                                                    <option value="Kürdəmir" @if($user->city == "Kürdəmir") selected @endif>Kürdəmir</option>
                                                    <option value="Qax" @if($user->city == "Qax") selected @endif>Qax</option>
                                                    <option value="Qazax" @if($user->city == "Qazax") selected @endif>Qazax</option>
                                                    <option value="Qəbələ" @if($user->city == "Qəbələ") selected @endif>Qəbələ</option>
                                                    <option value="Qobustan" @if($user->city == "Qobustan") selected @endif>Qobustan</option>
                                                    <option value="Quba" @if($user->city == "Quba") selected @endif>Quba</option>
                                                    <option value="Qubadlı" @if($user->city == "Qubadlı") selected @endif>Qubadlı</option>
                                                    <option value="Qusar" @if($user->city == "Qusar") selected @endif>Qusar</option>
                                                    <option value="Laçın" @if($user->city == "Laçın") selected @endif>Laçın</option>
                                                    <option value="Lerik" @if($user->city == "Lerik") selected @endif>Lerik</option>
                                                    <option value="Lənkəran" @if($user->city == "Lənkəran") selected @endif>Lənkəran</option>
                                                    <option value="Masallı" @if($user->city == "Masallı") selected @endif>Masallı</option>
                                                    <option value="Mingəçevir" @if($user->city == "Mingəçevir") selected @endif>Mingəçevir</option>
                                                    <option value="Naftalan" @if($user->city == "Naftalan") selected @endif>Naftalan</option>
                                                    <option value="Neftçala" @if($user->city == "Neftçala") selected @endif>Neftçala</option>
                                                    <option value="Oğuz" @if($user->city == "Oğuz") selected @endif>Oğuz</option>
                                                    <option value="Ordubad" @if($user->city == "Ordubad") selected @endif>Ordubad</option>
                                                    <option value="Saatlı" @if($user->city == "Saatlı") selected @endif>Saatlı</option>
                                                    <option value="Sabirabad" @if($user->city == "Sabirabad") selected @endif>Sabirabad</option>
                                                    <option value="Salyan" @if($user->city == "Salyan") selected @endif>Salyan</option>
                                                    <option value="Samux" @if($user->city == "Samux") selected @endif>Samux</option>
                                                    <option value="Siyəzən" @if($user->city == "Siyəzən") selected @endif>Siyəzən</option>
                                                    <option value="Sumqayıt" @if($user->city == "Sumqayıt") selected @endif>Sumqayıt</option>
                                                    <option value="Şabran" @if($user->city == "Şabran") selected @endif>Şabran</option>
                                                    <option value="Şahbuz" @if($user->city == "Şahbuz") selected @endif>Şahbuz</option>
                                                    <option value="Şamaxı" @if($user->city == "Şamaxı") selected @endif>Şamaxı</option>
                                                    <option value="Şəki" @if($user->city == "Şəki") selected @endif>Şəki</option>
                                                    <option value="Şəmkir" @if($user->city == "Şəmkir") selected @endif>Şəmkir</option>
                                                    <option value="Şərur" @if($user->city == "Şərur") selected @endif>Şərur</option>
                                                    <option value="Şirvan" @if($user->city == "Şirvan") selected @endif>Şirvan</option>
                                                    <option value="Şuşa" @if($user->city == "Şuşa") selected @endif>Şuşa</option>
                                                    <option value="Tərtər" @if($user->city == "Tərtər") selected @endif>Tərtər</option>
                                                    <option value="Tovuz" @if($user->city == "Tovuz") selected @endif>Tovuz</option>
                                                    <option value="Ucar" @if($user->city == "Ucar") selected @endif>Ucar</option>
                                                    <option value="Yardımlı" @if($user->city == "Yardımlı") selected @endif>Yardımlı</option>
                                                    <option value="Yevlax" @if($user->city == "Yevlax") selected @endif>Yevlax</option>
                                                    <option value="Zaqatala" @if($user->city == "Zaqatala") selected @endif>Zaqatala</option>
                                                    <option value="Zəngilan" @if($user->city == "Zəngilan") selected @endif>Zəngilan</option>
                                                    <option value="Zərdab" @if($user->city == "Zərdab") selected @endif>Zərdab</option>
                                                </select>